

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Conjuntos extends javax.swing.JFrame {

    /**
     * Creates new form Conjuntos
     */
    public Conjuntos() {
        initComponents();
        setLocationRelativeTo(null);
        fondo.setBorder(new Fondo());
    }
    operaciones obj = new operaciones();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuniverso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        btnFuncionescaracteristicas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txarespuesta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnunion = new javax.swing.JButton();
        btninterseccion = new javax.swing.JButton();
        btndiferenciaA = new javax.swing.JButton();
        btndiferenciaB = new javax.swing.JButton();
        btndiferenciasimetrica = new javax.swing.JButton();
        btnComplementoA = new javax.swing.JButton();
        btnComplementoB = new javax.swing.JButton();

        fondo.setBackground(new java.awt.Color(204, 204, 204));
        fondo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        fondo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("operacion de conjuntos ");

        jLabel3.setText("conjunto universo (U):");

        txtuniverso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuniversoKeyReleased(evt);
            }
        });

        jLabel4.setText("conjunto a (A)");

        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAKeyReleased(evt);
            }
        });

        jLabel5.setText("cojunto b (B)");

        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBKeyReleased(evt);
            }
        });

        btnFuncionescaracteristicas.setText("CREAR FUNCINES CARACTERISTICAS");
        btnFuncionescaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionescaracteristicasActionPerformed(evt);
            }
        });

        txarespuesta.setColumns(20);
        txarespuesta.setRows(5);
        jScrollPane1.setViewportView(txarespuesta);

        jLabel6.setText("RESULTADO ");

        btnunion.setText("A U B");
        btnunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunionActionPerformed(evt);
            }
        });

        btninterseccion.setText("A inter B");
        btninterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninterseccionActionPerformed(evt);
            }
        });

        btndiferenciaA.setText("A - B");
        btndiferenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiferenciaAActionPerformed(evt);
            }
        });

        btndiferenciaB.setText("B - A");
        btndiferenciaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiferenciaBActionPerformed(evt);
            }
        });

        btndiferenciasimetrica.setText("A O B");
        btndiferenciasimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiferenciasimetricaActionPerformed(evt);
            }
        });

        btnComplementoA.setText("COMP A");
        btnComplementoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplementoAActionPerformed(evt);
            }
        });

        btnComplementoB.setText("COMP B");
        btnComplementoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplementoBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuniverso)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(247, 247, 247)))
                        .addGap(66, 66, 66)
                        .addComponent(btnFuncionescaracteristicas))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnunion)
                                    .addComponent(btndiferenciaB))
                                .addGap(18, 18, 18)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btninterseccion)
                                    .addComponent(btndiferenciasimetrica))
                                .addGap(18, 18, 18)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnComplementoA)
                                    .addComponent(btndiferenciaA)))
                            .addComponent(btnComplementoB)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncionescaracteristicas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnunion)
                            .addComponent(btninterseccion)
                            .addComponent(btndiferenciaA))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndiferenciaB)
                            .addComponent(btndiferenciasimetrica)
                            .addComponent(btnComplementoA))
                        .addGap(18, 18, 18)
                        .addComponent(btnComplementoB)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionescaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionescaracteristicasActionPerformed
        // TODO add your handling code here:

       
        String U = this.txtuniverso.getText();
        String A = this.txtA.getText();
        String B = this.txtB.getText();
        obj = new operaciones(U,A,B);
        obj.funcarA();
        obj.funcarB();
        obj.funcarU();
    }//GEN-LAST:event_btnFuncionescaracteristicasActionPerformed

    private void btnunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunionActionPerformed
        // TODO add your handling code here:
        int[] Union = obj.Union(obj.getFa(), obj.getFb());
        String resp = obj.respuesta(Union);
        txarespuesta.setText(resp);
    }//GEN-LAST:event_btnunionActionPerformed

    private void btninterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninterseccionActionPerformed
        // TODO add your handling code here:
        int[] Interseccion = obj.Interseccion(obj.getFa(), obj.getFb());
        String resp = obj.respuesta(Interseccion);
        txarespuesta.setText(resp);
    }//GEN-LAST:event_btninterseccionActionPerformed

    private void btndiferenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiferenciaAActionPerformed
        // TODO add your handling code here:
        int[] diferenciaA = obj.diferenciaA(obj.getFa(), obj.getFb());
        String respuesta = obj.respuesta(diferenciaA);
        txarespuesta.setText(respuesta);
    }//GEN-LAST:event_btndiferenciaAActionPerformed

    private void btndiferenciaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiferenciaBActionPerformed
        // TODO add your handling code here:
        int[] diferenciaB = obj.diferenciaB(obj.getFa(), obj.getFb());
        String respuesta = obj.respuesta(diferenciaB);
        txarespuesta.setText(respuesta);
    }//GEN-LAST:event_btndiferenciaBActionPerformed

    private void btndiferenciasimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiferenciasimetricaActionPerformed
        // TODO add your handling code here:
        int[] diferenciaSimetrica = obj.diferenciaSimetrica(obj.getFa(), obj.getFb());
        String respuesta = obj.respuesta(diferenciaSimetrica);
        txarespuesta.setText(respuesta);
    }//GEN-LAST:event_btndiferenciasimetricaActionPerformed

    private void btnComplementoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplementoAActionPerformed
        // TODO add your handling code here:
        int[] ComplementoA = obj.ComplementoA(obj.getFu(), obj.getFa());
        String respuesta = obj.respuesta(ComplementoA);
        txarespuesta.setText(respuesta);
    }//GEN-LAST:event_btnComplementoAActionPerformed

    private void btnComplementoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplementoBActionPerformed
        // TODO add your handling code here:
        int[] ComplementoB = obj.ComplementoB(obj.getFu(), obj.getFb());
        String respuesta = obj.respuesta(ComplementoB);
        txarespuesta.setText(respuesta);                                   
    }//GEN-LAST:event_btnComplementoBActionPerformed

    private void txtuniversoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuniversoKeyReleased
        // TODO add your handling code here:
        String vec[] = txtuniverso.getText().split(",");
        String cad = "";
        if (vec.length >= 2) {
            String x = "";
            for (int j = 0; j < vec.length; j++) {
                x = vec[j];
                int con = 0;
                for (int i = 0; i < vec.length; i++) {
                    if (vec[i].equals(x)) {
                        con = con + 1;
                    }
                }
                if (con >= 2) {
                    JOptionPane.showMessageDialog(null, "No puede tener los mismos elementos");
                    for (int i = 0; i < vec.length - 1; i++) {
                        cad = cad + vec[i] + ",";
                    }
                    txtuniverso.setText(cad);
                    break;
                }
            }

        }
    }//GEN-LAST:event_txtuniversoKeyReleased

    private void txtAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyReleased
        // TODO add your handling code here:
          String v[] = txtuniverso.getText().split(",");
        String vec[] = txtA.getText().split(",");
        String cad = "";
        if (vec.length >= 2) {
            String x = "";
            for (int j = 0; j < vec.length; j++) {
                x = vec[j];
                int con = 0;
                for (int i = 0; i < vec.length; i++) {
                    if (vec[i].equals(x)) {
                        con = con + 1;
                    }
                }
                if (con >= 2) {
                    JOptionPane.showMessageDialog(null, "No puede tener los mismos elementos");
                    for (int i = 0; i < vec.length - 1; i++) {
                        cad = cad + vec[i] + ",";
                    }
                    txtA.setText(cad);
                    break;
                }
            }
        }
         boolean a = false;
        if (vec.length >= 1) {
            String e = vec[vec.length - 1];
            for (int i = 0; i < v.length; i++) {
                if (v[i].equals(e)) {
                    a = true;
                }
            }
            if (a == false) {
                JOptionPane.showMessageDialog(null, "Este elemento no pertenece al conjunto Universo.");
                for (int i = 0; i < vec.length - 1; i++) {
                    cad = cad + vec[i] + ",";
                }
                txtA.setText(cad);
            }
        }
    }//GEN-LAST:event_txtAKeyReleased

    private void txtBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyReleased
        // TODO add your handling code here:
        String v[] = txtuniverso.getText().split(",");
        String vec[] = txtB.getText().split(",");
        String cad = "";
        if (vec.length >= 2) {
            String x = "";
            for (int j = 0; j < vec.length; j++) {
                x = vec[j];
                int con = 0;
                for (int i = 0; i < vec.length; i++) {
                    if (vec[i].equals(x)) {
                        con = con + 1;
                    }
                }
                if (con >= 2) {
                    JOptionPane.showMessageDialog(null, "No puede tener los mismos elementos");
                    for (int i = 0; i < vec.length - 1; i++) {
                        cad = cad + vec[i] + ",";
                    }
                    txtB.setText(cad);
                    break;
                }
            }
        }
        boolean a = false;
        if (vec.length >= 1) {
            String e = vec[vec.length - 1];
            for (int i = 0; i < v.length; i++) {
                if (v[i].equals(e)) {
                    a = true;
                }
            }
            if (a == false) {
                JOptionPane.showMessageDialog(null, "Este elemento no pertenece al conjunto Universo.");
                for (int i = 0; i < vec.length - 1; i++) {
                    cad = cad + vec[i] + ",";
                }
                txtB.setText(cad);
            }
        }
    }//GEN-LAST:event_txtBKeyReleased

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conjuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conjuntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplementoA;
    private javax.swing.JButton btnComplementoB;
    private javax.swing.JButton btnFuncionescaracteristicas;
    private javax.swing.JButton btndiferenciaA;
    private javax.swing.JButton btndiferenciaB;
    private javax.swing.JButton btndiferenciasimetrica;
    private javax.swing.JButton btninterseccion;
    private javax.swing.JButton btnunion;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txarespuesta;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtuniverso;
    // End of variables declaration//GEN-END:variables
}
